<?php

namespace AppBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * LogroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogroRepository extends EntityRepository
{
}
