<?php

namespace AppBundle\Repository;

/**
 * ResguardoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResguardoRepository extends \Doctrine\ORM\EntityRepository
{
}
