<?php

namespace AppBundle\Repository;

/**
 * ValoracionesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ValoracionesRepository extends \Doctrine\ORM\EntityRepository
{
}
