parameters:
    college.name: INSTITUCION EDUCATIVA TAPITA
    college.subtitle: TRAS LAS HUELLAS DEL ULTIMO
    college.logo: itilogo.png
    college.dane: Código Dane: 8000265345 - Resolucion: 567567 del 23 de Febrero de 2016
    college.dir:  Calle 47 Nro 15 - 20
    college.tel:  3453453
    college.fax:  3453454
