<?php

/**
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Application\Sonata\UserBundle\Entity;

use Sonata\UserBundle\Entity\BaseUser as BaseUser;

/**
 * This file has been generated by the Sonata EasyExtends bundle.
 *
 * @link   https://sonata-project.org/bundles/easy-extends
 *
 * References :
 *   working with object :
 *   http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author <yourname> <youremail>
 */
class User extends BaseUser
{
	/**
	 * @var int $id
	 */
	protected $id;


	/**
	 * User constructor.
	 * Cuando un administrativo crea un estudiante desde dentro de la aplicacion
	 * automaticamente se crea el usuario de login para el estudiante.
	 *
	 * @param integer $username
	 * @param string  $email
	 * @param string  $password
	 *
	 */
	public function __construct ($username = null, $email = null, $password = null)
	{
		parent::__construct ();

		if ($username && $email && $password) {
			$this->username = $username;
			$this->email = $email;
			$this->password = $password;
		}

	}

	/**
	 * Get id
	 *
	 * @return int $id
	 */
	public function getId ()
	{
		return $this->id;
	}
}
