
BEGIN;
INSERT INTO area VALUES ('1', 'CIENCIAS NATURALES');
INSERT INTO area VALUES ('2', 'CIENCIAS SOCIALES');
INSERT INTO area VALUES ('3', 'EDUCACIÓN ARTÍSTICA');
INSERT INTO area VALUES ('4', 'EDUCACIÓN ÉTICA');
INSERT INTO area VALUES ('5', 'EDUCACIÓN RELIGIOSA');
INSERT INTO area VALUES ('6', 'EDUCACIÓN FÍSICA, RECREACIÓN Y DEPORTE');
INSERT INTO area VALUES ('7', 'HUMANIDADES');
INSERT INTO area VALUES ('8', 'MATEMÁTICAS');
INSERT INTO area VALUES ('9', 'TECNOLOGÍA E INFORMÁTICA');
INSERT INTO area VALUES ('10', 'CÁTEDRA EMPRESARIAL');
COMMIT;

