
BEGIN;
INSERT INTO tipo_documento VALUES ('1', 'REGISTRO CIVIL', 'RC');
INSERT INTO tipo_documento VALUES ('2', 'TARJETA DE INDENTIDAD', 'TI');
INSERT INTO tipo_documento VALUES ('3', 'CEDULA DE EXTRANJERIA', 'CE');
INSERT INTO tipo_documento VALUES ('4', 'CEDULA DE CIUDADANIA', 'CC');
INSERT INTO tipo_documento VALUES ('5', 'PASAPORTE', 'PA');
INSERT INTO tipo_documento VALUES ('6', 'MENOR SIN IDENTIFICACION', 'MS');
INSERT INTO tipo_documento VALUES ('7', 'ADULTO SIN IDENTIFICACION', 'AS');
INSERT INTO tipo_documento VALUES ('8', 'CARNET DIPLOMATICO', 'CD');
COMMIT;

